### PR TITLE
Flow router integration updates

### PR DESCRIPTION
**Pull request by PhilippSpo**
flow router update & added option to pass a function to the `displayName` property when adding a new field to the signUp view

### CODE REVIEW

**Comment by splendido** [comment]
What about getting rid of [this loop](https://github.com/PhilippSpo/core/blob/flow-router-integration/lib/core.js#L678), turn [this line](https://github.com/PhilippSpo/core/blob/flow-router-integration/lib/core.js#L645) into:

```javascript
AT.prototype.setupRoute = function(route, options) {
```

and call it from [here](https://github.com/PhilippSpo/core/blob/flow-router-integration/lib/core.js#L559):

```javascript
  this.setupRoute(route, options);
```

Otherwise, in case you set up more than one route, you're going to define the same route more than once...
Does this make sense?

**Comment by PhilippSpo** [comment]
Sure. Didn't really think about it yesterday night ;)
where should we move the `Meteor.isServer` [block](https://github.com/PhilippSpo/core/blob/flow-router-integration/lib/core.js#L646) in the `setupRoutes` function, so that it does only get executed once?

**Comment by PhilippSpo** [comment]
had this running the whole day while developing and didn't see any errors while signing up/in/out etc.

**Comment by splendido** [comment]
:+1:

**Pull request merged**
