### PR TITLE
adding documentation for AccountsTemplate.logout()

### PR DESCRIPTION
**Pull request by jxm262**
@splendido   Let me know if you want this labeled differently or placed in a different section of the guide.  I'm new to contributing on this project, but will gladly help out a bit more if you need anything :smile:

### CODE REVIEW

**Comment by jxm262** [comment]
referencing issue #430

**Comment by splendido** [comment]
LGTM!
...the only missing thing is a link to the paragraph from the initial *table of contents*?

**Comment by jxm262** [comment]
@splendido  ok just added to the TOC.  Let me know if there's anything else.  I'll take a look at the bug list later this weekend too :)

**Comment by splendido** [comment]
thanks!

**Pull request merged**
