### PR TITLE
White-list custom options object

### PR DESCRIPTION
**Pull request by dalgard**
As discussed in https://github.com/meteor-useraccounts/core/issues/242

### CODE REVIEW

**Comment by splendido** [comment]
Could you please update the [Form Fields Configuration](https://github.com/meteor-useraccounts/core#form-fields-configuration) section of the README accordingly and, possibly, add another section under [Advanced Customization](https://github.com/meteor-useraccounts/core#advanced-customization) to explain how you can overwrite default templates taking also advantage of this new option?

This would be great!

**Comment by dalgard** [comment]
I will look at it later today or tomorrow. Yesterday I found a somewhat tolerable method for configuring more complex layouts using the options object – I'm using the method in my code now, and will try to make an example of it.

**Comment by splendido** [comment]
Great, thanks!

**Comment by dalgard** [comment]
The example mentioned above can be found here:

https://gist.github.com/dalgard/a844f6569d8f471db9a7

**Comment by splendido** [comment]
don't forget to put in also a screen-shot! :)

**Comment by dalgard** [comment]
Added screenshot to gist

**Comment by dalgard** [comment]
Ffs...... I tried forking `core:master` using GitHub's features and now I don't know what's going on. The branch I'm working on (which GitHub has aptly named `patch-1`) is completely sync'ed with the upstream master without any conflicts.

I've only changed two files: `core.js` and `Guide.md`. Are you able to pull them? Should I try again from the beginning? Thanks.

**Comment by dalgard** [comment]
Closing this pull request and starting over..........

**Pull request closed without merging**
