### PR TITLE
Issue 229

### PR DESCRIPTION
**Pull request by Kestanous**
This should be ready for merge, unless there are more issues. It will not affect anything until the css packages are updated.

### CODE REVIEW

**Comment by splendido** [comment]
Hei Silvi, I'm sorry this remained lost among other issues...
I'll try to have a look at this tomorrow.

**Comment by Kestanous** [comment]
Actually hold up on that. Sure look at it but I have been thinking and maybe just the link would work. I happened to be logging into the iOS Tumblr app and their log in is absolutely beautiful. Before adding this we may want to revisit how devs configure the buttons and links.

**Comment by splendido** [comment]
:+1: 
Ok, lets try to break down things and design a new system for v2.0!

**Comment by splendido** [comment]
We'll reopen this in case we'll wish to proceed further!

**Pull request closed without merging**
