### PR TITLE
Update package.js

### PR DESCRIPTION
**Pull request by challett**
Version bump

### CODE REVIEW

**Comment by splendido** [comment]
for what? ;-)

**Comment by challett** [comment]
Would like the check in atremoveservice to be added to reduce the number of
exceptions my project throws

**Comment by splendido** [comment]
I'm sorry I have no idea what *atremoveservice* is...
Btw, I'm not sure whether just bumping the version number with no other change could resolve something.

**Comment by challett** [comment]
My apologies,  you merged a pull request of mine a while back which
resolved an issue with one of your methods not checking all inputs. I don't
think there was a version bump after which is why I am suggesting one

**Comment by challett** [comment]
#461

**Comment by splendido** [comment]
Oh, I see!
I'm sorry I've been away for a while...

I'll try to check new issues during the next days to see if there's something quick to fix, after this I'll publish a new version.

Thank you for your patience! ;-)

**Pull request closed without merging**
